# Generated by Django 6.0.2 on 2026-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('price', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
